### ISSUE TITLE
Cant open Showcase menu

### ISSUE THREAD

**Issue by Asha-Coding** [GhastCraftHD/Showcase#2]
I have an amethys, I just added the plugin, and I did Shift + Right click and it doesn't open anything, instead it gaves me Console errors

**Comment by GhastCraftHD** [comment]
Could you send me the errors, what version of the plusin you are using and what Minecraft Server version you are using? It could be that you use an older Minecraft version with the newest version of the plugin which might cause the issue

**Comment by Asha-Coding** [comment]
**I download Showcase-1.3.4 and my server version is Paper 1.20.4. Here is the console error. It's a bit long so I'll just send a part of it.**

03.09 18:29:18 [Server] ERROR Could not pass event PlayerInteractEvent to Showcase v1.3.4
03.09 18:29:18 [Server] INFO java.lang.NoSuchFieldError: Class org.bukkit.enchantments.Enchantment does not have member field 'org.bukkit.enchantments.Enchantment UNBREAKING'
03.09 18:29:18 [Server] INFO at de.leghast.showcase.ui.FrequentItems.addGlint(FrequentItems.java:24) ~[Showcase-1.3.4.jar:?]
03.09 18:29:18 [Server] INFO at de.leghast.showcase.ui.InterfaceItem.<init>(InterfaceItem.java:32) ~[Showcase-1.3.4.jar:?]
03.09 18:29:18 [Server] INFO at de.leghast.showcase.ui.InterfaceItem.<init>(InterfaceItem.java:36) ~[Showcase-1.3.4.jar:?]
03.09 18:29:18 [Server] INFO at de.leghast.showcase.ui.FrequentItems.addPageSwitchItems(FrequentItems.java:34) ~[Showcase-1.3.4.jar:?]
03.09 18:29:18 [Server] INFO at de.leghast.showcase.ui.page.PositionPage.getPositionPage(PositionPage.java:22) ~[Showcase-1.3.4.jar:?]
03.09 18:29:18 [Server] INFO at de.leghast.showcase.ui.UserInterface.<init>(UserInterface.java:17) ~[Showcase-1.3.4.jar:?]
03.09 18:29:18 [Server] INFO at de.leghast.showcase.handler.AdjusterInteractionHandler.handleAdjusterInteraction(AdjusterInteractionHandler.java:50) ~[Showcase-1.3.4.jar:?]
03.09 18:29:18 [Server] INFO at de.leghast.showcase.listener.PlayerInteractListener.onPlayerInteract(PlayerInteractListener.java:42) ~[Showcase-1.3.4.jar:?]
03.09 18:29:18 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor255.execute(Unknown Source) ~[?:?]
03.09 18:29:18 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
03.09 18:29:18 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
03.09 18:29:18 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
03.09 18:29:18 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:550) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:541) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1993) ~[?:?]
03.09 18:29:18 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
03.09 18:29:18 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
03.09 18:29:18 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
03.09 18:29:18 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
03.09 18:29:18 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
03.09 18:29:18 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
03.09 18:29:18 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
03.09 18:29:18 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
03.09 18:29:18 [Server] INFO at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by GhastCraftHD** [comment]
Okay, so the problem seems to be that you use an older version of Minecraft with the 1.21 version of the Plugin. You should be fine if you download version 1.3.3 from here. Let me know if that helped.

P.S. I know that this is suboptimal with the descriptions and stuff I am still trying to fix it :)

**Comment by Asha-Coding** [comment]
Ok thanks!

**Comment by GhastCraftHD** [comment]
Did that solve your issue?
